services:
  postgres:
    image: postgres:18.3
    container_name: work-from-home-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: work_from_home
      POSTGRES_USER: work_from_home
      POSTGRES_PASSWORD: work_from_home_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
